version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    envfile:
      - .env
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    envfile:
      - .env
    depends_on:
      - db
  migrations:
    build: .
    command: python manage.py makemigrations
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    envfile:
      - .env
    depends_on:
      - db