# Generated by Django 4.0.3 on 2022-03-21 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_photo_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.post'),
        ),
        migrations.AlterField(
            model_name='image',
            name='coords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.post'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='emoji',
            field=models.CharField(choices=[('smile', '😊'), ('☹', 'sad'), ('😂', 'lol'), ('😡', 'angry'), ('♥', 'hard')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='app.post'),
        ),
    ]
