# Generated by Django 4.0.3 on 2022-03-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_comment_post_alter_image_coords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='emoji',
            field=models.CharField(choices=[('smile', '😊'), ('sad', '☹'), ('lol', '😂'), ('angry', '😡'), ('hard', '♥')], max_length=50),
        ),
    ]
