# Generated by Django 4.0.3 on 2022-03-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_reaction_emoji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_add',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='date_add',
            new_name='date',
        ),
    ]
